name: caffeine_tracker
description: Track your caffeine intake and sleep better
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.1

  # Local DB
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1

  # AdMob
  google_mobile_ads: ^4.0.0

  # Charts
  fl_chart: ^0.65.0

  # Date/time
  intl: ^0.18.1

  # UI
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
